#!/bin/bash

set -Eeo pipefail

AWS_REGION=eu-west-2

function tf_plan {
  operation=$1

  terraform init
  terraform get # modules
  if [[ "${operation}" == "create" ]]; then
    cd modules/whitelist_lambda/lambda
    zip -r ../lambda.zip .
    cd ../../..
    terraform plan -var-file=terraform.tfvars -out="nhs_deployment.tfplan"
  elif [[ "${operation}" == "destroy" ]]; then
    terraform plan -var-file=terraform.tfvars -out="nhs_deployment.tfplan" -destroy
  else
    echo "Unknown operation (should be create or destroy), got: ${operation}"
    exit 1
  fi
}

function tf_apply {
  terraform init
  terraform get # modules
  terraform apply nhs_deployment.tfplan
  terraform output -json > tf-out.json
}

function _get_aws_ssm_secret {
  secret_id=$1
  json=$(aws ssm get-parameter --with-decryption --region $AWS_REGION --name $secret_id)
  if [ $? != 0 ]; then
    >&2 echo "Failed to obtain AWS secret from SSM: $secret_id"
    exit 5
  fi
  echo $json | jq -r ".Parameter.Value"
}

command="$1"
case "${command}" in
  tf)
      dojo "bash"
      ;;
  _tf_plan)
      tf_plan "$2"
      ;;
  tf_plan)
      dojo "./tasks _tf_plan $2"
      ;;
  _tf_apply)
      tf_apply
      ;;
  tf_apply)
      dojo "./tasks _tf_apply"
      ;;
  _tf_apply_whitelist)
      cd ip_whitelist
      terraform init
      terraform apply -auto-approve
      ;;
  tf_apply_whitelist)
      dojo "./tasks _tf_apply_whitelist"
      ;;
  _set_ip)
      my_ip=$(curl icanhazip.com)
      my_username="${DOJO_USER}"
      set +e
      aws ssm put-parameter \
       --region "${AWS_REGION}" \
       --name "/NHS/ip_whitelist/${my_username}/ipv4" \
       --type String \
       --overwrite \
       --value "${my_ip}"
      if [ $? != "0" ]; then
        echo "You need to authenticate with AWS first!"
        exit 5
      fi
      echo "Updated your IP to ${my_ip} at /NHS/ip_whitelist/${my_username}/ipv4"
      ;;
  set_ip) # To be used by developers when changing their IP
      dojo "./tasks _set_ip"
      ;;
  _trigger_pipeline)
      AUTHORIZATION_TOKEN=$(_get_aws_ssm_secret "/NHS/GoCD/prod/whitelist_auth_token")
      aws lambda invoke \
        --region "${AWS_REGION}" \
        --function-name ip-whitelist-trigger \
        --payload "{\"AUTHORIZATION_TOKEN\": \"$AUTHORIZATION_TOKEN\"}" \
        response.json
      ;;
  trigger_pipeline)
      dojo "./tasks _trigger_pipeline"
      ;;
  allow_my_ip)
      unset AWS_ACCESS_KEY_ID
      unset AWS_SECRET_ACCESS_KEY
      unset AWS_SESSION_TOKEN
      role_arn=$2
      mfa=$3
      if [ -z "${role_arn}" ]; then
        echo "Please specify admin role arn."
        echo "Usage:"
        echo "./tasks allow_my_ip <role_arn> <mfa-code>"
        exit 5
      fi
      if [ -z "${mfa}" ]; then
        echo "Please specify mfa-code"
        echo "Usage:"
        echo "./tasks allow_my_ip <role_arn> <mfa-code>"
        exit 5
      fi
      echo "Role ARN: $role_arn; MFA: $mfa"
      eval $(dojo "aws-cli-assumerole -rmfa ${role_arn} ${mfa}")
      ./tasks set_ip
      ./tasks trigger_pipeline
      ;;
  *)
      echo "Invalid command: '${command}'"
      exit 1
      ;;
esac
set +e
